---
nodes:
  - address: 10.20.30.10
    user: rancher
    role: [controlplane, etcd]
  - address: 10.20.30.11
    user: rancher
    role: [worker, etcd]
  - address: 10.20.30.12
    user: rancher
    role: [worker, etcd]
  - address: 10.20.30.13
    user: rancher
    role: [worker]

network:
    plugin: calico

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.10.3-rancher1-1
  kube-controller:
    image: rancher/k8s:v1.10.3-rancher1-1
  scheduler:
    image: rancher/k8s:v1.10.3-rancher1-1
  kubelet:
    image: rancher/k8s:v1.10.3-rancher1-1
  kubeproxy:
    image: rancher/k8s:v1.10.3-rancher1-1

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
  subjects:
  - kind: User
    name: system:serviceaccount:cattle-system:default
    apiGroup: rbac.authorization.k8s.io
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
  spec:
    rules:
    - http:
        paths:
        -   backend:
              serviceName: cattle-service
              servicePort: 80
        -   backend:
              serviceName: cattle-service
              servicePort: 443
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        containers:
        - image: rancher/rancher:master
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
